

<%@ Page Title="" Language="C#" MasterPageFile="MainMaster.master" AutoEventWireup="true" CodeBehind="Books.aspx.cs" Inherits="BooksApp.Default" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
           <title></title>
    <telerik:RadCodeBlock ID="RadCodeBlock1" runat="server">
	<script type="text/javascript">
        function rowDblClick(sender, eventArgs) {
            sender.get_masterTableView().editItem(eventArgs.get_itemIndexHierarchical());
        }
	</script>
</telerik:RadCodeBlock>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <br /><br /><br />

          <div style="align-items:center;text-align:center;width:79% !important; margin-left:60px;">

            <telerik:RadScriptManager runat="server" ID="RadScriptManager1"></telerik:RadScriptManager>

            <telerik:RadGrid ID="RadGrid1" runat="server" HorizontalAlign="Center" AllowAutomaticDeletes="True" AllowAutomaticInserts="True"
                AllowFilteringByColumn="True" AllowPaging="True" AllowSorting="True" AutoGenerateDeleteColumn="True"
                AutoGenerateEditColumn="True" DataSourceID="Books" PageSize="5" ShowFooter="True" Width="1687px"
                OnNeedDataSource="RadGrid1_NeedDataSource" 
                OnUpdateCommand="RadGrid1_UpdateCommand"
                OnItemCreated="RadGrid1_ItemCreated" 
                OnDeleteCommand="RadGrid1_DeleteCommand"
                OnInsertCommand="RadGrid1_InsertCommand"
                OnItemCommand="RadGrid1_ItemCommand" Height="300px"
                >
                

<GroupingSettings CollapseAllTooltip="Collapse all groups"></GroupingSettings>

                <ClientSettings AllowColumnsReorder="True" ReorderColumnsOnClient="True">
                    <Selecting AllowRowSelect="True" />
                </ClientSettings>

<MasterTableView AutoGenerateColumns="False" DataSourceID="Books" CommandItemDisplay="Top" DataKeyNames="BookId">
<RowIndicatorColumn ShowNoSortIcon="False" Visible="False"></RowIndicatorColumn>

<ExpandCollapseColumn ShowNoSortIcon="False" Created="True"></ExpandCollapseColumn>

    <Columns>
        <telerik:GridBoundColumn DataField="BookId" FilterControlAltText="Filter BookId column" HeaderText="BookId" ShowNoSortIcon="False" SortExpression="BookId" UniqueName="BookId" DataType="System.Int32" ReadOnly="True">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="BookName" FilterControlAltText="Filter BookName column" HeaderText="BookName" ShowNoSortIcon="False" SortExpression="BookName" UniqueName="BookName">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="BookPrice" DataType="System.Int32" FilterControlAltText="Filter BookPrice column" HeaderText="BookPrice" ShowNoSortIcon="False" SortExpression="BookPrice" UniqueName="BookPrice">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="BookCount" DataType="System.Int32" FilterControlAltText="Filter BookCount column" HeaderText="BookCount" ShowNoSortIcon="False" SortExpression="BookCount" UniqueName="BookCount">
        </telerik:GridBoundColumn>
    </Columns>

<EditFormSettings>
<EditColumn ShowNoSortIcon="False"></EditColumn>
</EditFormSettings>
    <PagerStyle AlwaysVisible="True" />
</MasterTableView>
                <PagerStyle AlwaysVisible="True" />
            </telerik:RadGrid>
            <asp:SqlDataSource ID="Books" runat="server" ConnectionString="<%$ ConnectionStrings:BooksConnectionString %>" OldValuesParameterFormatString="original_{0}" SelectCommand="SELECT [BookId], [BookName], [BookPrice], [BookCount] FROM [Books]">
            </asp:SqlDataSource>
            <telerik:RadInputManager ID="RadInputManager1" runat="server">
            </telerik:RadInputManager>
            <telerik:RadAjaxManager ID="RadAjaxManager1" runat="server" UpdateInitiatorPanelsOnly="True">
            </telerik:RadAjaxManager>
            <br />

        </div>

</asp:Content>